# Generated by Django 3.2.18 on 2023-06-01 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('studentid', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('mobile', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('receiptnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('checkoutid', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.CharField(blank=True, default='0000000000', max_length=255, null=True)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('TOKEN', 'TOKEN')], default='REGISTRATION', max_length=255)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studenttransactions', to='student.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertransactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
