# Generated by Django 3.2.18 on 2023-04-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_mpesacheckout_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Transaction',
        ),
    ]
