# Generated by Django 3.2.18 on 2023-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230402_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkoutid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
