# Generated by Django 3.2.18 on 2023-04-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_checkoutid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_joined',
        ),
    ]
