# Generated by Django 3.2.18 on 2023-04-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_transaction_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_deleted',
        ),
    ]
