# Generated by Django 3.2.18 on 2023-04-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('payments', '0007_remove_transaction_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE')], default='REGISTRATION', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
