# Generated by Django 3.2.18 on 2023-04-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230403_0737'),
        ('payments', '0008_auto_20230402_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='student.student'),
        ),
    ]
