# Generated by Django 3.2.18 on 2023-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20230403_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='userid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
