# Generated by Django 3.2.18 on 2023-04-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230403_0737'),
        ('payments', '0011_auto_20230403_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactioned',
        ),
        migrations.RenameField(
            model_name='transactioned',
            old_name='userid',
            new_name='studentid',
        ),
    ]
