# Generated by Django 3.2.18 on 2023-04-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230403_0737'),
        ('payments', '0012_auto_20230403_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactioned',
            new_name='Transaction',
        ),
    ]
