# Generated by Django 3.2.18 on 2023-04-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_transactioned_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('TOKEN', 'TOKEN')], default='REGISTRATION', max_length=255),
        ),
    ]
