# Generated by Django 3.2.18 on 2023-04-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230403_0847'),
        ('payments', '0014_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='student.student'),
        ),
    ]
