# Generated by Django 3.2.18 on 2023-04-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20230403_1309'),
        ('payments', '0016_auto_20230403_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studenttransactions', to='student.soko'),
        ),
    ]
