# Generated by Django 3.2.18 on 2023-04-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_transaction_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='student',
        ),
    ]
