# Generated by Django 3.2.18 on 2023-04-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_student'),
        ('payments', '0018_remove_transaction_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studenttransactions', to='student.student'),
        ),
    ]
