# Generated by Django 3.2.18 on 2023-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.CharField(blank=True, default='0000000000', max_length=255, null=True),
        ),
    ]
