# Generated by Django 3.2.18 on 2023-04-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0022_alter_student_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('tokensused', models.FloatField(max_length=255)),
                ('minutesused', models.FloatField(max_length=255)),
                ('mobilecalled', models.CharField(max_length=255)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
