# Generated by Django 3.2.18 on 2023-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('callstamp', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('tokensused', models.FloatField(max_length=255)),
                ('minutesused', models.FloatField(max_length=255)),
                ('mobileused', models.CharField(blank=True, default='0700000000', max_length=255, null=True)),
                ('mobilecalled', models.CharField(max_length=255)),
                ('personcalled', models.CharField(blank=True, default='Admin', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
