# Generated by Django 3.2.18 on 2023-04-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='mobileused',
            field=models.CharField(blank=True, default='0700000000', max_length=255, null=True),
        ),
    ]
