# Generated by Django 3.2.18 on 2023-04-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_mobileused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='timestamp',
            new_name='callstamp',
        ),
    ]
