# Generated by Django 3.2.18 on 2023-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_rename_timestamp_call_callstamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='personcalled',
            field=models.CharField(blank=True, default='Admin', max_length=255, null=True),
        ),
    ]
