# Generated by Django 3.2.18 on 2023-04-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
        ('school', '0002_auto_20230402_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='mobile',
            field=models.OneToOneField(default='0000000000', on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mobile.mobile'),
        ),
    ]
