# Generated by Django 3.2.18 on 2023-04-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_active'),
        ('school', '0003_alter_school_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='mobile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mobile.mobile'),
        ),
    ]
