# Generated by Django 3.2.18 on 2023-05-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_minutesconsumed'),
        ('school', '0008_alter_schoolwebcreate_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolwebcreate',
            name='mobile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schoolwebcreate', to='mobile.mobile'),
        ),
    ]
