# Generated by Django 3.2.18 on 2023-05-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_minutesconsumed'),
        ('school', '0009_alter_schoolwebcreate_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mobile.mobile'),
        ),
    ]
