# Generated by Django 3.2.18 on 2023-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_minutesconsumed'),
        ('school', '0010_alter_school_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='mobile',
        ),
        migrations.AddField(
            model_name='school',
            name='mobile',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='mobile.Mobile'),
        ),
    ]
