# Generated by Django 3.2.18 on 2023-05-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_minutesconsumed'),
        ('school', '0011_auto_20230514_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='mobile',
        ),
        migrations.AddField(
            model_name='school',
            name='mobile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='mobile.mobile'),
        ),
    ]
