# Generated by Django 3.2.18 on 2023-04-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_user_contact_useractive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobileone',
            new_name='mobile',
        ),
    ]
