# Generated by Django 3.2.18 on 2023-04-04 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_rename_mobileone_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='useractive',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
