# Generated by Django 3.2.18 on 2023-04-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_useractive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='useractive',
            new_name='contactuser',
        ),
    ]
