# Generated by Django 3.2.18 on 2023-05-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_useractive_contact_contactuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_created']},
        ),
    ]
