# Generated by Django 3.2.18 on 2023-05-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_minutesconsumed'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobileminutes', to='mobile.mobile')),
            ],
        ),
    ]
