# Generated by Django 3.2.18 on 2023-04-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='active',
            field=models.BooleanField(default=True, max_length=255),
        ),
    ]
