# Generated by Django 3.2.18 on 2023-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='tokensconsumed',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
