# Generated by Django 3.2.18 on 2023-05-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_mobile_tokensconsumed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'ordering': ['-date_created']},
        ),
    ]
