# Generated by Django 3.2.18 on 2023-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_mobile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='minutesconsumed',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
