# Generated by Django 3.2.18 on 2023-04-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('kcpeindexnumber', models.CharField(max_length=255)),
                ('registrationnumber', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('tokenbalance', models.FloatField(default=0.0)),
                ('totalnumberofcalls', models.FloatField(default=0.0)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
            ],
        ),
    ]
