# Generated by Django 3.2.18 on 2023-06-01 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255)),
                ('kcpeindexnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('registrationnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False, max_length=255)),
                ('activefromdate', models.DateTimeField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default='one', max_length=255, null=True)),
                ('confirmpassword', models.CharField(blank=True, default='one', max_length=255, null=True)),
                ('tokenbalance', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalnumberofcalls', models.FloatField(blank=True, default=0.0, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.ManyToManyField(default=None, related_name='students', to='contact.Contact')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
