# Generated by Django 3.2.18 on 2023-04-02 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('PARENT', 'PARENT'), ('GUARDIAN', 'GUARDIAN'), ('SPONSOR', 'SPONSOR')], default='PARENT', max_length=255)),
                ('mobileone', models.CharField(max_length=255)),
                ('mobiletwo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='userid',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='contacts',
            field=models.ManyToManyField(related_name='students', to='student.Contacts'),
        ),
    ]
