# Generated by Django 3.2.18 on 2023-04-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_contacts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
