# Generated by Django 3.2.18 on 2023-04-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230403_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('PARENT', 'PARENT'), ('GUARDIAN', 'GUARDIAN'), ('SPONSOR', 'SPONSOR')], default='PARENT', max_length=255)),
                ('mobileone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobiletwo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='contacts',
            field=models.ManyToManyField(related_name='students', to='student.Contact'),
        ),
    ]
