# Generated by Django 3.2.18 on 2023-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230403_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='activefromdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
