# Generated by Django 3.2.18 on 2023-04-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230402_1526'),
        ('payments', '0016_auto_20230403_0936'),
        ('student', '0008_auto_20230403_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
