# Generated by Django 3.2.18 on 2023-04-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230402_1526'),
        ('payments', '0016_auto_20230403_0936'),
        ('student', '0009_rename_student_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='poted',
        ),
    ]
