# Generated by Django 3.2.18 on 2023-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20230403_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255)),
                ('kcpeindexnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('registrationnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False, max_length=255)),
                ('activefromdate', models.DateTimeField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('confirmpassword', models.CharField(max_length=255)),
                ('tokenbalance', models.FloatField(blank=True, default=0.0, null=True)),
                ('totalnumberofcalls', models.FloatField(blank=True, default=0.0, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
