# Generated by Django 3.2.18 on 2023-04-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230402_1526'),
        ('payments', '0017_alter_transaction_student'),
        ('student', '0013_auto_20230403_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='soko',
            name='contacts',
            field=models.ManyToManyField(related_name='students', to='student.Contact'),
        ),
        migrations.AddField(
            model_name='soko',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school'),
        ),
    ]
