# Generated by Django 3.2.18 on 2023-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20230403_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soko',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='soko',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
