# Generated by Django 3.2.18 on 2023-04-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_transaction_student'),
        ('student', '0015_auto_20230403_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soko',
        ),
    ]
