# Generated by Django 3.2.18 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contacts',
            field=models.ManyToManyField(default=True, null=True, related_name='students', to='student.Contact'),
        ),
    ]
