# Generated by Django 3.2.18 on 2023-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('student', '0020_alter_student_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='student',
            name='contacts',
            field=models.ManyToManyField(default=True, null=True, related_name='students', to='contact.Contact'),
        ),
    ]
