# Generated by Django 3.2.18 on 2023-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('student', '0021_auto_20230404_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contacts',
            field=models.ManyToManyField(default=None, related_name='students', to='contact.Contact'),
        ),
    ]
