# Generated by Django 3.2.18 on 2023-04-05 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0023_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='ab8d263e-b923-450c-90cb-d3da99fcd2ff', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='appuser.appuser'),
            preserve_default=False,
        ),
    ]
