# Generated by Django 3.2.18 on 2023-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('isstudent', models.BooleanField(default=False)),
                ('isadmin', models.BooleanField(default=False)),
                ('isparent', models.BooleanField(default=False)),
                ('isagent', models.BooleanField(default=False)),
            ],
        ),
    ]
