# Generated by Django 3.2.18 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_auto_20230401_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
