# Generated by Django 3.2.18 on 2023-04-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0005_auto_20230401_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
