# Generated by Django 3.2.18 on 2023-04-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230402_1526'),
        ('appuser', '0006_appuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='school.school'),
        ),
    ]
