# Generated by Django 3.2.18 on 2023-04-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0007_appuser_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['-date_created']},
        ),
    ]
