# Generated by Django 3.2.18 on 2023-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activationamount', models.IntegerField(blank=True, default=0, null=True)),
                ('tokennumber', models.IntegerField(blank=True, default=1, null=True)),
                ('minutespertokenOrequivalentminutes', models.FloatField(default=0, max_length=255)),
                ('minutepershilling', models.FloatField(default=0, max_length=255)),
                ('shillingspertokenOrequivalentshillings', models.FloatField(blank=True, default=0, max_length=255, null=True)),
            ],
        ),
    ]
