# Generated by Django 3.2.18 on 2023-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('activationamount', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('tokennumber', models.IntegerField(blank=True, default=1, max_length=255, null=True)),
                ('shillingspertokenOrequivalentshillings', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('minutespertokenOrequivalentminutes', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('minutepershilling', models.FloatField(blank=True, default=0, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
