# Generated by Django 3.2.18 on 2023-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='tokennumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
