# Generated by Django 3.2.18 on 2023-04-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_auto_20230406_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='shillingspertokenOrequivalentshillings',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
