# Generated by Django 3.2.18 on 2023-04-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_alter_constant_shillingspertokenorequivalentshillings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='activationamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
