# Generated by Django 3.2.18 on 2023-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_auto_20230406_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
