# Generated by Django 3.2.18 on 2023-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0006_alter_constant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
