# Generated by Django 3.2.18 on 2023-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0008_alter_constant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='schoolid',
            field=models.IntegerField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
