# Generated by Django 3.2.18 on 2023-05-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolwebcreate_mobile'),
        ('constants', '0010_alter_constant_schoolid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='schoolid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
