# Generated by Django 3.2.18 on 2023-05-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolwebcreate_mobile'),
        ('constants', '0013_alter_constant_schoolid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constant',
            name='schoolid',
        ),
        migrations.AddField(
            model_name='constant',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constants', to='school.school'),
        ),
    ]
