# Generated by Django 3.2.18 on 2023-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0014_auto_20230511_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constant',
            options={},
        ),
        migrations.RemoveField(
            model_name='constant',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='constant',
            name='date_updated',
        ),
    ]
