# Generated by Django 3.2.18 on 2023-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0015_auto_20230512_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
