# Generated by Django 3.2.18 on 2023-06-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('tokenamount', models.IntegerField(blank=True, default=0, null=True)),
                ('equivalentshillings', models.FloatField(blank=True, default=0, null=True)),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='school.school')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
