# Generated by Django 3.2.18 on 2023-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='equivalentshillings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
