# Generated by Django 3.2.18 on 2023-05-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_equivalentshillings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-date_created']},
        ),
    ]
