# Generated by Django 3.2.18 on 2023-05-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolwebcreate_mobile'),
        ('tokens', '0003_alter_token_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='school.school'),
        ),
    ]
